# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/gts3l-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter gts3llte gts3lwifi,$(TARGET_DEVICE)),)

endif
